//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServNOWY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kat_Zywnosc
    {
        public Kat_Zywnosc()
        {
            this.Zywnosc = new HashSet<Zywnosc>();
        }
    
        public int idkat_zywnosc { get; set; }
        public string Nazwa_kat { get; set; }
    
        public virtual ICollection<Zywnosc> Zywnosc { get; set; }
    }
}
