//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServNOWY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kat_przepis
    {
        public Kat_przepis()
        {
            this.Przepis = new HashSet<Przepis>();
        }
    
        public int idKat_przepis { get; set; }
        public string nazwa_kat_prze { get; set; }
    
        public virtual ICollection<Przepis> Przepis { get; set; }
    }
}
