//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServNOWY.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spizarnia
    {
        public Spizarnia()
        {
            this.SkladnikiWSpizarni = new HashSet<SkladnikiWSpizarni>();
        }
    
        public int idSpizarnia { get; set; }
        public string Nazwa { get; set; }
        public string nr_seryjny { get; set; }
        public Nullable<int> idUzytkownik { get; set; }
    
        public virtual ICollection<SkladnikiWSpizarni> SkladnikiWSpizarni { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
    }
}
