//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServNOWY.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A172D4_slowo2017Entities : DbContext
    {
        public DB_A172D4_slowo2017Entities()
            : base("name=DB_A172D4_slowo2017Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kat_przepis> Kat_przepis { get; set; }
        public virtual DbSet<Kat_Zywnosc> Kat_Zywnosc { get; set; }
        public virtual DbSet<Przepis> Przepis { get; set; }
        public virtual DbSet<SkladnikiDoPrzepisu> SkladnikiDoPrzepisu { get; set; }
        public virtual DbSet<SkladnikiWSpizarni> SkladnikiWSpizarni { get; set; }
        public virtual DbSet<Spizarnia> Spizarnia { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Uzytkownik> Uzytkownik { get; set; }
        public virtual DbSet<Zywnosc> Zywnosc { get; set; }
    }
}
