//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServNOWY.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Zywnosc
    {
        public Zywnosc()
        {
            this.SkladnikiDoPrzepisu = new HashSet<SkladnikiDoPrzepisu>();
            this.SkladnikiWSpizarni = new HashSet<SkladnikiWSpizarni>();
        }
    
        public int idZywnosc { get; set; }
        public string Nazwa { get; set; }
        public int idkat_zywnosc { get; set; }
        [JsonIgnore]
        public virtual Kat_Zywnosc Kat_Zywnosc { get; set; }
        [JsonIgnore]
        public virtual ICollection<SkladnikiDoPrzepisu> SkladnikiDoPrzepisu { get; set; }
        [JsonIgnore]
        public virtual ICollection<SkladnikiWSpizarni> SkladnikiWSpizarni { get; set; }
    }
}
